# Generated by Django 5.1.7 on 2025-06-10 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WEB', '0003_alter_grupofamiliar_sexo_delete_registroentrada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('firma', 'Firma Digital'), ('huella', 'Huella Digital'), ('geo', 'Geolocalización')], max_length=20)),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitud_salida', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud_salida', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('firma_digital', models.TextField(blank=True, null=True)),
                ('huella_id', models.CharField(blank=True, max_length=100, null=True)),
                ('huella_validada', models.BooleanField(default=False)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('es_retraso', models.BooleanField(default=False)),
                ('minutos_retraso', models.IntegerField(default=0)),
                ('es_horas_extra', models.BooleanField(default=False)),
                ('minutos_horas_extra', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_asistencia', to='WEB.registroempresas')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('registro_asistencia', 'Acceso al módulo de asistencia')],
            },
        ),
    ]
