# Generated by Django 5.1.7 on 2025-03-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0002_alter_userfingerprint_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfingerprint',
            name='quality',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
