# Generated by Django 5.1.7 on 2025-03-25 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0003_alter_userfingerprint_quality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfingerprint',
            name='registered_at',
        ),
        migrations.AlterField(
            model_name='userfingerprint',
            name='quality',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfingerprint',
            name='template',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='userfingerprint',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
