# Generated by Django 5.1.5 on 2025-02-13 00:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('habilitado', 'Habilitado'), ('suspendido', 'Plan Suspendido')], default='habilitado', max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('max_usuarios', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEB.provincia')),
            ],
        ),
        migrations.AddField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEB.region'),
        ),
        migrations.CreateModel(
            name='RegistroEmpresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cliente', models.CharField(max_length=20, unique=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('giro', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('oficina', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('web', models.URLField(blank=True)),
                ('vigente', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('aldia', 'Al día'), ('atrasado', 'Atrasado'), ('suspendido', 'Plan Suspendido')], default='aldia', max_length=20)),
                ('rut_representante', models.CharField(max_length=12)),
                ('nombre_representante', models.CharField(max_length=100)),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('celular_contacto', models.CharField(max_length=20)),
                ('mail_contacto', models.EmailField(max_length=254)),
                ('limite_usuarios', models.PositiveIntegerField(default=0)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WEB.comuna')),
                ('plan_contratado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='WEB.plan')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WEB.provincia')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WEB.region')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='VigenciaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('monto_plan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_plan', models.CharField(max_length=50, unique=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vigencias', to='WEB.registroempresas')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WEB.plan')),
            ],
            options={
                'verbose_name': 'Vigencia de Plan',
                'verbose_name_plural': 'Vigencias de Planes',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('trabajador', 'Trabajador')], default='trabajador', max_length=20)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='WEB.registroempresas')),
                ('groups', models.ManyToManyField(blank=True, help_text='Grupos a los que pertenece el usuario', related_name='usuario_groups', to='auth.group', verbose_name='groups')),
                ('permisos', models.ManyToManyField(blank=True, related_name='usuarios', to='WEB.registropermisos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario', related_name='usuario_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('permitir_otra_entrada', models.BooleanField(default=False)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Entrada',
                'verbose_name_plural': 'Registros de Entrada',
                'ordering': ['-hora_entrada'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEB.registroempresas')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Cambios',
                'verbose_name_plural': 'Historial de Cambios',
                'ordering': ['-fecha'],
            },
        ),
    ]
