# Generated by Django 5.1.5 on 2025-01-31 04:24

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrotrabajador',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='registrotrabajador',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='registrosupervisor',
            name='rut',
            field=models.CharField(default='00000000-0', max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='registrotrabajador',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='registrotrabajador',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='registrotrabajador',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='trabajador_groups', related_query_name='trabajador', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='registrotrabajador',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='registrotrabajador',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='registrotrabajador',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='registrotrabajador',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='registrotrabajador',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='registrotrabajador',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
        migrations.AddField(
            model_name='registrotrabajador',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='trabajador_permissions', related_query_name='trabajador', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='registrotrabajador',
            name='username',
            field=models.CharField(default='default_username', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='registroempresas',
            name='rut',
            field=models.CharField(default='00000000-0', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='registrotrabajador',
            name='rut',
            field=models.CharField(default='00000000-0', max_length=12, unique=True),
        ),
    ]
