# Generated by Django 5.1.5 on 2025-02-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroempresas',
            name='celular',
            field=models.CharField(blank=True, default='000000012', max_length=20),
        ),
        migrations.AlterField(
            model_name='registroempresas',
            name='celular_contacto',
            field=models.CharField(default='000000001', max_length=20),
        ),
        migrations.AlterField(
            model_name='registroempresas',
            name='telefono',
            field=models.CharField(default='0000000230', max_length=20),
        ),
    ]
