# Generated by Django 5.1.7 on 2025-04-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroentrada',
            name='firma_digital',
            field=models.TextField(blank=True, null=True),
        ),
    ]
