# Generated by Django 5.1.5 on 2025-02-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registropermisos',
            options={},
        ),
        migrations.RemoveField(
            model_name='registropermisos',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='registropermisos',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
