# Generated by Django 5.1.5 on 2025-02-05 01:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0002_alter_registroempresas_celular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VigenciaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('indefinido', models.BooleanField(default=False)),
                ('monto_plan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vigencias', to='WEB.registroempresas')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WEB.plan')),
            ],
        ),
    ]
