# Generated by Django 5.1.7 on 2025-06-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0002_registroentrada_latitud_salida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupofamiliar',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'masculino'), ('FEMENINO', 'femenino')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='RegistroEntrada',
        ),
    ]
