# Generated by Django 5.1.6 on 2025-02-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0002_alter_registropermisos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroempresas',
            name='estado',
            field=models.CharField(choices=[('aldia', 'Al día'), ('atrasado', 'Atrasado'), ('suspendido', 'Suspendido')], default='aldia', max_length=20),
        ),
    ]
