# Generated by Django 5.1.5 on 2025-03-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0002_auditoriaacceso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('eliminar_trabajador', 'Permiso para eliminar trabajadores'), ('eliminar_supervisor', 'Permiso para eliminar supervisores'), ('eliminar_admin', 'Permiso para eliminar administradores'), ('crear_admin', 'Permiso para crear administradores'), ('crear_supervisor', 'Permiso para crear supervisores'), ('crear_trabajador', 'Permiso para crear trabajadores'), ('editar_supervisor', 'permiso para editar supervisores'), ('editar_trabajador', 'permiso para editar trabajadores')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
