# Generated by Django 5.1.5 on 2025-03-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0003_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroempresas',
            options={'permissions': [('crear_empresa', 'Puede crear empresas'), ('eliminar_empresa', 'Puede eliminar empresas'), ('detalles_empresa', 'Puede ver detalles de empresas'), ('lista_empresas', 'Puede listar empresas'), ('vista_empresas', 'Puede ver las empresas'), ('vista_planes', 'Puede ver los planes'), ('crear_plan', 'Puede crear los planes')], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='permisos',
        ),
    ]
