# Generated by Django 5.1.5 on 2025-01-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0003_remove_registrosupervisor_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('trabajador', 'Trabajador')], default='trabajador', max_length=20),
        ),
    ]
