# Generated by Django 5.1.7 on 2025-06-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0003_alter_grupofamiliar_sexo_delete_registroentrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroempresas',
            name='frecuencia_pago',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], default='mensual', max_length=20),
        ),
    ]
