# Generated by Django 5.1.7 on 2025-04-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0003_usuario_vigencia_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='vigenciaplan',
            name='max_usuarios_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
