# Generated by Django 5.1.6 on 2025-02-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0003_alter_registroempresas_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vigenciaplan',
            name='estado',
            field=models.CharField(choices=[('indefinido', 'Indefinido'), ('mensual', 'Mensual')], default='indefinido', max_length=20),
        ),
    ]
