# Generated by Django 5.1.7 on 2025-06-16 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0004_registroempresas_frecuencia_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='dias_descanso',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='dias_trabajo',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='inicio_turno',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='horario',
        ),
        migrations.AddField(
            model_name='turno',
            name='duracion_ciclo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='es_rotativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='inicio_turno',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DiaTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_ciclo', models.IntegerField(blank=True, null=True)),
                ('dia_semana', models.IntegerField(blank=True, null=True)),
                ('es_descanso', models.BooleanField(default=False)),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WEB.horario')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='WEB.turno')),
            ],
            options={
                'unique_together': {('turno', 'dia_ciclo'), ('turno', 'dia_semana')},
            },
        ),
    ]
