# Generated by Django 5.1.7 on 2025-04-08 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0004_vigenciaplan_max_usuarios_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='vigencia_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='WEB.vigenciaplan'),
        ),
    ]
