# Generated by Django 5.1.5 on 2025-03-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0004_alter_registroempresas_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroPermisos',
        ),
    ]
