# Generated by Django 5.1.5 on 2025-01-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0004_remove_usuario_rol_usuario_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registropermisos',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='permisos',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='WEB.registropermisos'),
        ),
    ]
