# Generated by Django 5.1.5 on 2025-02-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0004_comuna_provincia_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='precio_original',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=10),
            preserve_default=False,
        ),
    ]
