# Generated by Django 5.1.5 on 2025-02-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0005_plan_descuento_plan_precio_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='descuento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='precio_original',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
