# Generated by Django 5.1.6 on 2025-02-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0005_alter_vigenciaplan_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vigenciaplan',
            name='estado',
            field=models.CharField(choices=[('indefinido', 'Indefinido'), ('mensual', 'Mensual')], default='indefido', max_length=20),
        ),
    ]
