# Generated by Django 5.1.7 on 2025-04-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0005_alter_usuario_vigencia_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='modulos_habilitados',
            field=models.ManyToManyField(blank=True, related_name='supervisores', to='WEB.vigenciaplan', verbose_name='Módulos Habilitados'),
        ),
    ]
