# Generated by Django 5.1.5 on 2025-03-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0005_delete_registropermisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('trabajador', 'Trabajador')], default='admin', max_length=20),
        ),
    ]
