# Generated by Django 5.1.6 on 2025-02-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0006_alter_vigenciaplan_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellidoM',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
