# Generated by Django 5.1.7 on 2025-06-16 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0006_turno_horario_fijo_alter_diaturno_horario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='duracion_ciclo',
            new_name='dias_descanso',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='es_rotativo',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='horario_fijo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='inicio_turno',
        ),
        migrations.AddField(
            model_name='turno',
            name='dias_trabajo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='inicio_turno',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='WEB.horario'),
        ),
        migrations.CreateModel(
            name='AsignacionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WEB.horario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_diarias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'fecha')},
            },
        ),
        migrations.DeleteModel(
            name='DiaTurno',
        ),
    ]
