# Generated by Django 5.1.5 on 2025-02-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0006_alter_plan_descuento_alter_plan_precio_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='valor',
            field=models.IntegerField(default=0),
        ),
    ]
