# Generated by Django 5.1.5 on 2025-03-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0006_alter_usuario_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'permissions': [('Registrar_pago', 'permite registar un pago')]},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'permissions': [('crear_plan', 'Puede crear los planes'), ('vista_planes', 'Puede listar los planes')], 'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AlterModelOptions(
            name='registroempresas',
            options={'permissions': [('crear_empresa', 'Puede crear empresas'), ('eliminar_empresa', 'Puede eliminar empresas'), ('detalles_empresa', 'Puede ver detalles de empresas'), ('lista_empresas', 'Puede listar empresas'), ('vista_empresas', 'Puede ver las empresas'), ('vista_planes', 'Puede ver los planes'), ('crear_plan', 'Puede crear los planes'), ('generar_boleta', 'puede generar boletas'), ('vista_servicios', 'puede ver los servicios y editarlos'), ('vista_estadisticas', 'puede ver las estadusticas de las empresas')], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
