# Generated by Django 5.1.7 on 2025-04-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0006_usuario_modulos_habilitados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='modulos_habilitados',
        ),
    ]
