# Generated by Django 5.1.5 on 2025-02-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0006_registroentrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroentrada',
            name='hora_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
