# Generated by Django 5.1.7 on 2025-04-21 17:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0007_remove_usuario_modulos_habilitados'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroentrada',
            name='es_horas_extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroentrada',
            name='es_retraso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroentrada',
            name='minutos_horas_extra',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroentrada',
            name='minutos_retraso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='metodo_registro_permitido',
            field=models.CharField(choices=[('firma', 'Firma Digital'), ('huella', 'Huella Digital'), ('geo', 'Geolocalización')], default='firma', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('tolerancia_retraso', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('tolerancia_horas_extra', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='WEB.registroempresas')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='WEB.horario'),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dias_trabajo', models.IntegerField()),
                ('dias_descanso', models.IntegerField()),
                ('inicio_turno', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='WEB.registroempresas')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='WEB.turno'),
        ),
    ]
