# Generated by Django 5.1.6 on 2025-02-17 15:22

import WEB.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0007_usuario_apellidom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroempresas',
            name='rut',
            field=models.CharField(max_length=13, unique=True, validators=[WEB.validators.validar_rut]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[WEB.validators.validar_rut]),
        ),
        migrations.AlterField(
            model_name='vigenciaplan',
            name='estado',
            field=models.CharField(choices=[('indefinido', 'Indefinido'), ('mensual', 'Mensual'), ('suspendio', 'Suspendido')], default='indefido', max_length=20),
        ),
    ]
