# Generated by Django 5.1.5 on 2025-02-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0007_alter_plan_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='precio_original',
        ),
        migrations.AlterField(
            model_name='plan',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
