# Generated by Django 5.1.5 on 2025-02-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0007_registroentrada_hora_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroentrada',
            name='permitir_otra_entrada',
            field=models.BooleanField(default=False),
        ),
    ]
