# Generated by Django 5.1.6 on 2025-02-18 16:08

import WEB.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0008_alter_registroempresas_rut_alter_usuario_rut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, max_length=12, unique=True, validators=[WEB.validators.validar_rut]),
        ),
    ]
