# Generated by Django 5.1.5 on 2025-03-14 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0008_alter_registroentrada_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroentrada',
            options={'permissions': [('registro_asistencia', 'Acceso al módulo de asistencia')]},
        ),
        migrations.AddField(
            model_name='registroentrada',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_asistencia', to='WEB.registroempresas'),
        ),
        migrations.AlterField(
            model_name='registroentrada',
            name='metodo',
            field=models.CharField(choices=[('firma', 'Firma Digital'), ('huella', 'Huella Digital'), ('geo', 'Geolocalización')], max_length=20),
        ),
    ]
