# Generated by Django 5.1.7 on 2025-04-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0008_registroentrada_es_horas_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='tipo_horario',
            field=models.CharField(choices=[('diurno', 'Diurno'), ('nocturno', 'Nocturno'), ('mixto', 'Mixto')], default='diurno', max_length=20),
        ),
    ]
