# Generated by Django 5.1.5 on 2025-02-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0008_registroentrada_permitir_otra_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroempresas',
            name='limite_supervisores',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='registroempresas',
            name='limite_trabajadores',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
