# Generated by Django 5.1.5 on 2025-02-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0008_remove_plan_descuento_remove_plan_precio_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroempresas',
            name='vigente',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
