# Generated by Django 5.1.7 on 2025-05-08 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0009_horario_tipo_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialnotificaciones',
            name='vigencia_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WEB.vigenciaplan'),
        ),
    ]
