# Generated by Django 5.1.5 on 2025-03-17 12:47

import WEB.views.scripts.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0009_alter_registroentrada_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroempresas',
            name='rut_representante',
            field=models.CharField(max_length=12, unique=True, validators=[WEB.views.scripts.validators.validators.validar_rut]),
        ),
    ]
