# Generated by Django 5.1.6 on 2025-02-19 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0009_alter_usuario_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroempresas',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registroempresas',
            name='frecuencia_pago',
            field=models.CharField(blank=True, choices=[('mensual', 'Mensual'), ('anual', 'Anual')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registroempresas',
            name='metodo_pago',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='registroempresas',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registroempresas',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('ahorro', 'Ahorro'), ('corriente', 'Corriente')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vigenciaplan',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('pagado', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='WEB.registroempresas')),
                ('vigencia_planes', models.ManyToManyField(related_name='pagos_asociados', to='WEB.vigenciaplan')),
            ],
        ),
    ]
