# Generated by Django 5.1.5 on 2025-03-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0010_alter_registroempresas_rut_representante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroempresas',
            name='plan_contratado',
        ),
    ]
