# Generated by Django 5.1.6 on 2025-02-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0010_registroempresas_banco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vigenciaplan',
            name='activo',
        ),
        migrations.AlterField(
            model_name='vigenciaplan',
            name='estado',
            field=models.CharField(choices=[('indefinido', 'Indefinido'), ('mensual', 'Mensual'), ('suspendido', 'Suspendido')], default='indefinido', max_length=20),
        ),
    ]
