# Generated by Django 5.1.5 on 2025-03-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0011_remove_registroempresas_plan_contratado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroempresas',
            options={'permissions': [('crear_empresa', 'Puede crear empresas'), ('eliminar_empresa', 'Puede eliminar empresas'), ('detalles_empresa', 'Puede ver detalles de empresas'), ('lista_empresas', 'Puede listar empresas'), ('vista_empresas', 'Puede ver las empresas'), ('vista_planes', 'Puede ver los planes'), ('generar_boleta', 'puede generar boletas'), ('vista_servicios', 'puede ver los servicios y editarlos'), ('vista_estadisticas', 'puede ver las estadusticas de las empresas')], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AddField(
            model_name='registroempresas',
            name='planes',
            field=models.ManyToManyField(related_name='empresas', through='WEB.VigenciaPlan', to='WEB.plan'),
        ),
    ]
