# Generated by Django 5.1.5 on 2025-03-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0013_remove_cobro_vigencias_planes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellidoM',
        ),
    ]
