# Generated by Django 5.1.6 on 2025-02-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0013_alter_pago_fecha_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('received_date', models.DateTimeField()),
                ('procesado', models.BooleanField(default=False)),
            ],
        ),
    ]
