# Generated by Django 5.1.5 on 2025-03-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0014_remove_usuario_apellidom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
    ]
