# Generated by Django 5.1.7 on 2025-03-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0015_remove_usuario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroentrada',
            name='huella_validada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroentrada',
            name='precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='huella_credential',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
