# Generated by Django 5.1.5 on 2025-03-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0015_pago_created_at_pago_observaciones_pago_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('automatico', 'Automático'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('credito', 'Crédito'), ('debito', 'Débito'), ('abono', 'Abono'), ('efectivo', 'Efectivo')], max_length=20),
        ),
    ]
