# Generated by Django 5.1.7 on 2025-03-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0017_cobro_vigencias_planes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroempresas',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='registroempresas',
            name='frecuencia_pago',
        ),
        migrations.RemoveField(
            model_name='registroempresas',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='registroempresas',
            name='numero_cuenta',
        ),
        migrations.RemoveField(
            model_name='registroempresas',
            name='tipo_cuenta',
        ),
    ]
