# Generated by Django 5.1.5 on 2025-03-04 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0017_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cobro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='WEB.cobro'),
        ),
        migrations.AlterField(
            model_name='cobro',
            name='vigencia_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cobros_relacionados', to='WEB.vigenciaplan'),
        ),
    ]
