# Generated by Django 5.1.5 on 2025-03-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0018_pago_cobro_alter_cobro_vigencia_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='vigencias_planes',
            field=models.ManyToManyField(blank=True, related_name='cobros_planes', to='WEB.vigenciaplan'),
        ),
    ]
