# Generated by Django 5.1.7 on 2025-03-18 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0018_remove_registroempresas_banco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroempresas',
            name='limite_usuarios',
        ),
    ]
