# Generated by Django 5.1.5 on 2025-03-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0019_cobro_vigencias_planes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
