# Generated by Django 5.1.7 on 2025-03-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0019_remove_registroempresas_limite_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='huella_credential',
        ),
    ]
